name: C Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build
        run: make
      - name: Test template creation (dry run)
        run: ./cst 2 c letters || ./cst 2 c l
        env:
          HOME: ${{ github.workspace }}
      - name: Clean
        run: make clean
